name: "iot"

x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  zigbee2mqtt:
    image: "11notes/zigbee2mqtt:2.13.0"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
    networks:
      frontend:
    volumes:
      - "zigbee2mqtt.etc:/zigbee2mqtt/etc"
    restart: "always"

volumes:
  zigbee2mqtt.etc:

networks:
  frontend: